[book]
authors = ["m0003r"]
language = "ru"
multilingual = false
src = "src"
title = "Python для Рины"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
curly-quotes = true
mathjax-support = true